INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME, CATEGORY_DESCRIPTION) VALUES (1,'CATEGORY A', 'Items related with category A');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME, CATEGORY_DESCRIPTION) VALUES (2,'CATEGORY B', 'Items related with category B');

INSERT INTO ITEM (ITEM_ID, DESCRIPTION, QUANTITY, CATEGORY_ID) VALUES (1, 'ITEM A', 10, 1);
INSERT INTO ITEM (ITEM_ID, DESCRIPTION, QUANTITY, CATEGORY_ID) VALUES (2, 'ITEM B', 10, 2);
INSERT INTO ITEM (ITEM_ID, DESCRIPTION, QUANTITY, CATEGORY_ID) VALUES (3, 'ITEM C', 10, 1);